- lib/convection/model/template/resource.rb
To use this with an array property do the following:
property :vpc_security_groups, 'VPCSecurityGroups', :array
This will initialize `@properties['VPCSecurityGroups']` to an empty Array,
then adds elements to `@properties['VPCSecurityGroups']` as
`vpc_security_groups` is called within the dsl.
> Adds support for Arrays in the property helper

- lib/convection/model/template/resource/aws_rds_db_instance.rb
For Nexpose, we want our RDS instances to have encryption enabled.
I created a PR on top of hamer-time. Seems razor-convection is dependent on this branch from github.
> Add an RDS option to allow encryption.

- lib/convection/control/cloud.rb
This allows us to diff a new stack that hasn't yet been converged.  This
is useful to do a last verification before converging.
> Diff new stack

- lib/convection/model/template/resource/aws_iam_role.rb
Created trust_flow_logs that will set the correct trust permissions of flow log iam roles.
> Core-1172 trust flow logs

- lib/convection/model/template/resource/aws_rds_db_instance.rb
This adds support for encryption at rest for RDS instance types which support the feature.
On a related note, AWS::EC2::Volume needs to be created to be able to support this globally for all EC2 instances which support disk encryption.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-ebs-volume.html
> Add support for encryption at rest for RDS.

- lib/convection/model/template/resource/aws_sqs_queue_policy.rb
SQS policies are similar to S3 and SNS. No reason for SQS policies to deviate from SQS and S3
> Allow SQS policy to be defined like S3 policies.

- lib/convection/model/template/resource.rb
- lib/convection/model/template/resource/aws_cloudfront_distribution.rb
- lib/convection/model/template/resource_property/aws_cloudfront_cachebehavior.rb
- lib/convection/model/template/resource_property/aws_cloudfront_customerrorresponse.rb
- lib/convection/model/template/resource_property/aws_cloudfront_customorigin.rb
- lib/convection/model/template/resource_property/aws_cloudfront_defaultcachebehavior.rb
- lib/convection/model/template/resource_property/aws_cloudfront_distribution_config.rb
- lib/convection/model/template/resource_property/aws_cloudfront_forwardedvalues.rb
- lib/convection/model/template/resource_property/aws_cloudfront_georestriction.rb
- lib/convection/model/template/resource_property/aws_cloudfront_logging.rb
- lib/convection/model/template/resource_property/aws_cloudfront_origin.rb
- lib/convection/model/template/resource_property/aws_cloudfront_restrictions.rb
- lib/convection/model/template/resource_property/aws_cloudfront_s3origin.rb
- lib/convection/model/template/resource_property/aws_cloudfront_viewercertificate.rb
This adds the `AWS::CloudFront::Distribution` type and sub-types.
This allows specifying CloudFront configuration similar to:
```ruby
cloudfront_distribution 'FooDistro' do
config do
cname 'stuff.example.com'
default_root_object 'index.html'
price_class 'PriceClass_100'
default_cache_behavior do
forwarded_values do
query_string false
end
target_origin 's3-stuff-example-com'
viewer_protocol_policy 'redirect-to-https'
end
origin do
id 's3-stuff-example-com'
domain_name "stuff.example.com.s3-website-#{stack.region}.amazonaws.com"
custom_origin do
protocol_policy 'http-only'
end
end
viewer_certificate do
iam_certificate 'AAABBB111222'
minimum_protocol_version 'TLSv1'
ssl_support_method 'sni-only'
end
end
end
```
> Add CloudFront Support

- lib/convection/model/template/resource/aws_iam_managed_policy.rb
This takes advantage of the existing Policy mixin.
A Managed policy is very similar to a role policy in that there is
deny/allow statements.  The difference is that a Managed policy has one
and only one policy.
For example this is what a policy might look like:
iam_managed_policy 'MyPolicy' do
path '/my/path'
allow do
resource ARN
action 's3:GetObject'
end
group 's3-users'
end
> Adds IAM Managed Policy

- lib/convection/model/template/resource/aws_s3_bucket.rb
Summary of Change
================
The S3 Property for Versioning was incorrect. This updates the property to match the name documented in the CloudFormation documentation.
Usage Example
============
Enabling Versioning:
```ruby
s3_bucket 'MyVersionedBucket' do
bucket_name 'MyVersionedBucket'
versioning_configuration('Status': 'Enabled')
end
```
Disabling Versioning:
```ruby
s3_bucket 'MyVersionedBucket' do
bucket_name 'MyVersionedBucket'
versioning_configuration('Status': 'Suspended')
end
```
> Fix S3 Versioning Property Name.

- example/security-groups.rb
- lib/convection/model/template/resource/aws_ec2_security_group.rb
This changes the `egress_rule` method signature to take a destination.
You have always been able to set the destination of an egress rule using a block like:
```ruby
egress_rule(:tcp, 22) { self.destination = '0.0.0.0/0' }
```
This makes it a little easier by allowing you to set it in the method itself like:
```ruby
egress_rule(:tcp, 22, '0.0.0.0/0')
```
Additionally, this PR changes security rules to only specify a port if a port is declared.  This allows specifying rules that have no to/from port, like the following rule that is [recommended](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html) by Amazon for removing the default egress rule.
```ruby
egress_rule(-1, nil, '127.0.0.1/32')
```
> Change egress_rule signature

- example/Cloudfile
- example/foobar.rb
- example/instances.rb
- lib/convection/model/template/resource.rb
- lib/convection/model/template/resource/aws_ec2_instance.rb
- lib/convection/model/template/resource/aws_ec2_volume.rb
- lib/convection/model/template/resource/aws_kms_key.rb
- lib/convection/model/template/resource_property/aws_ec2_block_device_mapping.rb
- lib/convection/model/template/resource_property/aws_ec2_block_store_block_device.rb
- lib/convection/model/template/resource_property/aws_ec2_mount_point.rb
This adds support for adding volumes to EC2 instances.  It allows adding ephemeral instances, unencrypted EBS instances, and encrypted EBS instances.
The easiest way to see these changes is in the `example/foobar.rb` file.  I'll copy/paste the relevant/new sections here:
```ruby
kms_key 'FoobarKmsKey' do
description 'Used to encrypt volumes'
deletion_policy 'Retain'
policy do
allow do
sid 'Enable IAM User Permissions'
principal :AWS => ["arn:aws:iam::#{MY_AWS_ACCOUNT_NUMBER}:root"]
action 'kms:*'
resource '*'
end
end
end
ec2_volume 'FoobarEncryptedVol' do
availability_zone 'us-east-1a'
size 20
volume_type :gp2
encrypted true
kms_key fn_ref('FoobarKmsKey')
deletion_policy 'Snapshot'
end
ec2_instance 'FoobarWithEncryptedVol' do
image_id stack['foobar-image']
instance_type 'm3.medium' …
```
> Add instance volumes

- example/vpc.rb
- lib/convection/model/template/resource/aws_ec2_eip.rb
- lib/convection/model/template/resource/aws_ec2_nat_gateway.rb
- lib/convection/model/template/resource/aws_ec2_route.rb
This allows you to create a NAT gateways using AWS' new [NAT Gateway](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html) support.
A NAT Gateway looks like:
```ruby
ec2_eip "NatGatewayIP1" do
domain 'vpc'
end
ec2_nat_gateway "NatGateway1" do
subnet fn_ref("TargetVPCSubnetPublic1")
allocation_id get_att("NatGatewayIP1", 'AllocationId')
end
ec2_route "NatGatewayRoute1" do
destination '0.0.0.0/0'
nat_gateway fn_ref("NatGateway1")
route_table_id private_table
end
```
> Add support for NAT gateways

- lib/convection/model/template/resource/aws_lambda_function.rb
- lib/convection/model/template/resource_property/aws_lambda_function_code.rb
- lib/convection/model/template/resource_property/aws_lambda_vpc_config.rb
- test/convection/model/test_lambdas.rb
Added full support for S3 bucket reference, and VPC integration.  Unit test added, showing we can support:
```
lambda_function 'TestLambda' do
description 'Test description'
handler 'index.handler'
runtime 'nodejs'
role 'arn:aws:x:y:z'
code do
s3_bucket 'testbucket'
s3_key 'testkey'
end
vpc_config do
security_groups %w(group1 group2)
subnets %w(subnet1a subnet1b)
end
end
```
> Fix support for Lambdas

- lib/convection/model/template/resource/aws_elasticache_cluster.rb
- lib/convection/model/template/resource/aws_elasticache_replication_group.rb
This pr is for adding the mixin and render method to add tag support to elasticache clusters and elasticache replication groups
> tag support for elasticache cluster and replication group

- lib/convection/model/template/resource/aws_iam_role.rb
- test/convection/model/test_trust.rb
Within an `iam_role` definition, I can now specify:
`trust_ec2_instances`
or
`trust_service 'ec2'`
This means any other services can be supported without an explicit `trust_XXX` method. e.g.
`trust_service 'lambda'`
I need the Lambda trust method above.  This will generate:
```
"AssumeRolePolicyDocument": {
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"sts:AssumeRole"
],
"Principal": {
"Service": "lambda.amazonaws.com"
}
}
]
}
```
> Generic trust relationship

- lib/convection/model/template/resource/aws_events_rule.rb
- lib/convection/model/template/resource_property/aws_events_rule_target.rb
Adds a resource for `AWS::Events::Rule` to enable Convection support of creating CloudWatch event rules.
See also [AWS::Events::Rule](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern).
> Create a CloudWatch events rule resource

- lib/convection/model/template/resource/aws_directory_service_simple_ad.rb
- test/convection/model/test_directory_service.rb
ping @jmanero-r7 @athompson-r7 @abegley-r7 @simonirwin-r7 
---
```ruby
resource 'SimpleActiveDirectory' do
type 'AWS::DirectoryService::SimpleAD'
property 'Description',  'Example simple AD'
property 'EnableSso',    false
property 'Name',         'ExampleSimpleAD'
property 'Password',     'directory.password'
property 'ShortName',    'directory.name'
property 'Size',         'Small'
property 'VpcSettings', {
'SubnetIds' => ['subnet-deadb33f'],
'VpcId'     => 'vpc-deadb33f'
}
end
```
```ruby
directoryservice_simple_ad 'SimpleActiveDirectory' do
description  'Example simple AD'
enable_sso   false
name         'ExampleSimpleAD'
password     'directory.password'
short_name   'directory.name'
size         'Small'
vpc_settings 'SubnetIds', ['subnet-deadb33f']
vpc_settings 'VpcId', …
```
> Create a simple directory service (SimpleAD) resource

- lib/convection/model/template/resource/aws_ec2_vpc_endpoint.rb
- test/convection/model/test_vpc_endpoint.rb
The join was creating something like this:
`com.amazonaws.us-east-1s3`
It should be:
`com.amazonaws.us-east-1.s3`
> VPC Endpoint error when generating the S3 service name

- bin/convection
This adds verbosity options to the diff command.
~~~text
$> convection help diff
Usage:
convection diff
Options:
--v, [--verbose], [--no-verbose]             # Show stack progress
--vv, [--very-verbose], [--no-very-verbose]  # Show unchanged stacks
[--cloudfile=CLOUDFILE]
Show changes that will be applied by converge
~~~
The default behavior is to only show stacks that have changes. If nothing changes, the diff command won't output anything. Stacks that have changes show both the "compare  Compare local state of stack XXX with remote template" line and the changes.
~~~text
$> convection diff
compare  Compare local state of stack YYY with remote template
create  .Resources.Role.Properties.Policies.0.PolicyDocument.Statement.2.Effect: Allow
create …
> Feature: diff verbosity options

- Gemfile
This will prevent TravisCI builds from failing when RuboCop rules change
drastically in MINOR versions. PATCH versions will still be allowed to
be pulled automatically.
👮 👮 👮 
Fix #124.
See also #123.
> 👮🏽 Constrain RuboCop to ~> 0.40.0

- bin/convection
- lib/convection/control/cloud.rb
This makes the `convection diff` command behave the same way the `convection converge` command does. It takes an optional `STACK` argument, the name of the stack to diff up to. If the stack name's given, the diff will halt at the named stack.
> Feature: Diff individual stacks

- lib/convection/model/template/resource/aws_iam_role.rb
Closes #93.
---
~~**NOTE**: These changes will update the names for most of these policies.~~
*edit*: Changes to maintain the policy names were implemented.
> Reimplement AWS trust service methods after merging #92

- .rubocop_todo.yml
- lib/convection/control/stack.rb
- test/convection/tasks/test_after_update_tasks.rb
- test/convection/tasks/test_before_update_tasks.rb
- test/test_helper.rb
Fix #130:
>- [x] Create a new `before_update` task category
>- [x] Create a new `after_update` task category
>- [x] Run update tasks before/after the update phase
>
>See also https://github.com/rapid7/convection/issues/114 and https://github.com/rapid7/convection/issues/120.
> Fix #130 - Support after_update/before_update task types

- lib/convection/model/template/resource/aws_ec2_customer_gateway.rb
- lib/convection/model/template/resource/aws_ec2_vpn_connection.rb
- lib/convection/model/template/resource/aws_ec2_vpn_connection_route.rb
- lib/convection/model/template/resource/aws_ec2_vpn_gateway.rb
- lib/convection/model/template/resource/aws_ec2_vpn_gateway_route_propagation.rb
- lib/convection/model/template/resource/aws_route53_hosted_zone.rb
I'd like to revisit this at some stage to add some sugar to more easily link up the different resources.
Need to add an example to the docs, too.
> Support vpn

- lib/convection/control/stack.rb
- lib/convection/model/template/resource.rb
We are extending convection to allow composing multiple CloudFormation resources into custom resources (or "resource groups") that contain custom business logic.  This PR adds a couple of simple improvements that make extending much easier.  These fixes should largely be a no-op for regular convection usage.
* 29d1c233812fa40560550e10103831ccd3e10a72 - Always preform a two-pass compilation of stacks.  The first pass checks for syntax errors and allows stacks with custom resources to compile.  This makes sure we fail fast.  It also allows stacks earlier in the dependency tree to access class variables from stacks later in the dependency tree.  This is useful for solving chicken-and-egg problems like ensuring we create security groups before attaching them in other stacks.  Our experiments …
> Add improvements useful for convection extensions

- lib/convection/model/template/resource/aws_s3_bucket.rb
See also https://github.com/rapid7/convection/commit/782208968f#diff-7126ecd8a0f873d6bdeffcaf269fb9a7R15 where this typo was introduced.
cc @jmanero-r7 @athompson-r7 @simonirwin-r7 @abegley-r7
> Fix a typo in the aws_s3_bucket.rb resource

- lib/convection/model/template/resource/aws_s3_bucket.rb
- lib/convection/model/template/resource_property/aws_s3_cors_configuration.rb
- lib/convection/model/template/resource_property/aws_s3_cors_configuration_rule.rb
These changes are required to support setting the CorsConfiguration through convection.
---
cc @abegley-r7 @simonirwin-r7 @mmckeaveney-r7
> Support s3 bucket configuration types

- lib/convection/model/template/resource/aws_iam_user.rb
See also #141.
Same as in `aws_iam_role`.
> Fix #141 - Define the managed_policy_arn property for the iam_user resource

- Gemfile
Use `yardoc` to generate documentation under `doc/`.
> Add yard (yardoc.org) to Gemfile

- lib/convection/control/stack.rb
- lib/convection/model/event.rb
Fix #146.
<pre>ecarey ~/r/b/example-cloud (master)> bundle exec convection converge
converge  Stack vpc
update_in_progress  ecarey-test-cloud-1-vpc: (AWS::CloudFormation::Stack/arn:aws:cloudformation:eu-west-1:...:stack/ecarey-test-cloud-1-vpc/...) User Initiated
update_in_progress  TargetVPC: (AWS::EC2::VPC/vpc-deadb33f) 
update_complete  TargetVPC: (AWS::EC2::VPC/vpc-deadb33f) 
update_complete_cleanup_in_progress  ecarey-test-cloud-1-vpc: (AWS::CloudFormation::Stack/arn:aws:cloudformation:eu-west-1:...:stack/ecarey-test-cloud-1-vpc/...) 
update_complete  ecarey-test-cloud-1-vpc: (AWS::CloudFormation::Stack/arn:aws:cloudformation:eu-west-1:...:stack/ecarey-test-cloud-1-vpc/...) 
<b>task_in_progress  Task (after_update) validate-vpc-stack-outputs in progress for stack vpc.
task_complete …
> Fix #146 - Emit events around lifecycle tasks

- bin/convection
- lib/convection/control/cloud.rb
Additionally fixes:
* A bad Thor type in `--stacks` for the `converge` subcommand.
* Some grammar/wording.
> Restore early return functionality of diff/converge (lost in #169)

- bin/convection
- lib/convection/control/cloud.rb
- lib/convection/control/stack.rb
Previously we did not expose the `Stack#delete` command in our CLI. Adds a `delete` subcommand that functions like the `diff`/`converge` commands.
> Support deleting stacks using `convection delete`

- lib/convection/control/cloud.rb
When a instance of each stack is created it resolves a bunch of information about that stack. If the request fails because of rate limiting we do not collect the needed info. Then when doing a diff we may assume the stack does not exist or certain attributes are not set and display them as changes. This change will collect errors encountered and display them before discontinuing the diff.
Example
```
$ convection diff
error  Error(s) during stack diff Rate exceeded
```
Verification Steps
> When doing a diff print errors found during stack initialization

- lib/convection/control/cloud.rb
- lib/convection/control/stack.rb
- lib/convection/model/cloudfile.rb
This should speed up diffs by about 2 seconds per stack
Use the retry logic provided by the aws sdk. See here https://github.com/aws/aws-sdk-ruby/blob/ef9f2d3655c4bacb3adff580a6b295df510f78fe/aws-sdk-core/lib/aws-sdk-core/plugins/retry_errors.rb#L16 and https://github.com/aws/aws-sdk-ruby/blob/a3a442e0824318dcd95021a1f6057309518bf2a5/aws-sdk-core/spec/aws/s3/client_spec.rb#L15
A custom retry limit can be set in the cloudfile like below or it defaults to 6 which is a ~19 second sleep
```
retry_limit YOUR_NUMBER
```
Verification Steps
> Use retry limit

- lib/convection/control/cloud.rb
- lib/convection/control/stack.rb
- lib/convection/model/cloudfile.rb
Resolve stack information in parallel. This should cut the init time down almost in half. The number of threads can be set in the cloudfile with the thread_count option. The default of 2 seems to provide the best gain for the least amount of rate limiting.
> Parallel initialisation

- lib/convection/model/template/resource/aws_s3_bucket.rb
- lib/convection/model/template/resource_property/aws_s3_replication_configuration.rb
- lib/convection/model/template/resource_property/aws_s3_replication_configuration_rule.rb
- lib/convection/model/template/resource_property/aws_s3_replication_configuration_rule_destination.rb
See [PD-8267](https://issues.corp.rapid7.com/browse/PD-8267)
Resource properties to support [S3 replication configuration](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-replicationconfiguration) (configuration for replicating objects in an S3 bucket).
> PD-8267 adding support for S3 cross region replication.

- lib/convection.rb
- lib/convection/control/stack.rb
Reverts rapid7/convection#174.
See also https://github.com/rapid7/convection/pull/182 around why this implementation did not give us the intended functionality change.
> Revert "Retry expired credentials"

- lib/convection/model/template/resource/aws_auto_scaling_auto_scaling_group.rb
- spec/convection/model/template/resource/aws_auto_scaling_auto_scaling_group_spec.rb
Fix #194 by accepting a new, optional,`:propagate_at_launch` parameter in calls to the `AutoScalingGroup#tag` method.
In CloudFormation the [Auto Scaling Tags type](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-tags.html#cfn-as-tags-PropagateAtLaunch) includes an additional `PropagateAtLaunch` property.
```ruby
tag 'MyTagName', 'MyValue', propagate_at_launch: true
```
Run `bundle exec spec` after checking out 796bde2 and 8795d93 and note the two failures found in 796bde2 being resolved once we update the `AutoScalingGroup#tag` method to include a new parameter. Also notice that the existing specs still pass.
> Fix #194 - support autoscaling tags

- lib/convection/control/stack.rb
- lib/convection/model/cloudfile.rb
Fix accidental overloading of status. This causes issues in converge as in_progress? needs status and calls the incorrect one(mine).
Converges are broken
Converges work again
> Fix accidental overloading of status breaking converges

- lib/convection/model/template.rb
- spec/convection/model/template/condition_spec.rb
- spec/convection/model/template/template_spec.rb
- spec/convection/model/template/validate_bytesize_spec.rb
Fix #198 - Warn users of when they redefine resources.
> Fix #198 - Warn users of manually creating predefined resources

- lib/convection/dsl/intrinsic_functions.rb
- lib/convection/model/template/output.rb
- lib/convection/model/template/resource.rb
Fix #196 - Add support for the new `Export` `Outputs` property and the `Fn::ImportValue` function.
* See also the [Fn::ImportValue](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-importvalue.html) documentation.
* See also the [Export section of the Outputs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) documentation.
To simplify cross-stack references written in Convection templates by leveraging the new addition to CloudFormation.
> Fix #196 - Support cross stack references

- bin/convection
Define a new `#emit_events` auxiliary method for printing out `Model::Diff` and `Model::Event` events.
> Fix #204 - Define a no_commands helper #emit_events

- bin/convection
```sh
$ convection describe-tasks
Stack vpc (acmecorp-test-0-vpc) includes the following tasks:
0. associated private zones with VPC in acmecorp-test-0-vpc
1. unassociated private zones with VPC in acmecorp-test-0-vpc
Stack sessioncache (acmecorp-test-0-sessioncache) includes the following tasks:
0. Tasks::TagElastiCache
```
```sh
$ convection describe-tasks --stacks vpc
Stack vpc (acmecorp-test-0-vpc) includes the following tasks:
0. associated private zones with VPC in acmecorp-test-0-vpc
1. unassociated private zones with VPC in acmecorp-test-0-vpc
```
```sh
$ convection run-tasks
No value provided for required options '--stack'
```
```sh
$ convection run-tasks --stack vpc
Using the "platform-dev" environment configuration for all operations.
The following tasks are available to …
```
> Fix #207 - Define subcommands for describing/running stack tasks

- bin/convection
- convection.gemspec
- docs/getting-started.md
- docs/index.md
- lib/convection/control/cloud.rb
Fix #203 - This adds the ability to converge or diff multiple cloudfiles at the same time.
Aids in deploying to multiple regions.
```
bundle exec convection diff --cloudfiles us-east-1/Cloudfile eu-central-1/Cloudfile
bundle exec convection converge --cloudfiles us-east-1/Cloudfile eu-central-1/Cloudfile
```
> Parallel cloudfile diffs and converges

- lib/convection/control/cloud.rb
- lib/convection/control/stack.rb
Fix #189.
Add `Stack#credential_error?` for testing whether all the errors present
are credential errors (if there are other errors handle regularly).
> Fix #189 - Introduce a more explicit error around expired credentials

- bin/convection
Fix #212.
Specify the `:cloudfile` thor method option to all task subcommands vs. depending on the obsoleted thor class option.
> Fix #212 - Specify --cloudfile for task subcommands

- .gitignore
- lib/convection/model/template/resource/aws_s3_bucket.rb
- lib/convection/model/template/resource_property/aws_cloudfront_defaultcachebehavior.rb
- lib/convection/model/template/resource_property/aws_s3_website_configuration.rb
- lib/convection/model/template/resource_property/aws_s3_website_configuration_redirect_all_requests_to.rb
- lib/convection/model/template/resource_property/aws_s3_website_configuration_routing_rule.rb
- lib/convection/model/template/resource_property/aws_s3_website_configuration_routing_rule_redirect_rule.rb
- lib/convection/model/template/resource_property/aws_s3_website_configuration_routing_rule_routing_rule_condition.rb
Add ability to specify a website_configuration to an s3 bucket.  To do correctly, this required creating a number of resource_property types to support the various options that CloudFormation gives.
This change is necessary to enable static website hosting for an s3 bucket.
s3_bucket 'bucketName' do
...
website_configuration do
index_document 'index.html'
redirect_all_requests_to do
host_name 'somehost.example.com'
protocol 'https'
end
end
end
> Add S3 Website Configuration and properties

- lib/convection/model/template/resource/aws_route53_recordset.rb
Changes alias_target and geo_location in a route53_recordset to allow either json or a resource_property
Previously, users needed to specify the json for alias_target and
geo_location for a route53_recordset.  In the add-alb branch, merged in
PR 214, this was changed in a backwards-incompatible way, requiring
anyone who had previously specified json to now specify a block for the
resource_property.  Now, either way is acceptable.
This is potentially a paradigm that can be used elsewhere, as there are
many places where a resource_property would be appropriate, but has not
existed and users have implemented the functionality directly with a
json (or ruby hash) object.  This will allow us to deprecate that method
in favor of the more clean resource_property approach, without breaking …
> Maintain backwards compatability with route53

- lib/convection/model/template/resource/aws_elbv2_target_group.rb
Adds the ability, suggested by @erran-r7 to specify target_group_attributes and matcher for an elbv2 target group.
Old way:
matcher do
http_code 200
end
target_group_attribute do
key 'deregistration_delay.timeout_seconds'
value 300
end
New way:
matcher 200
target_group_attribute 'deregistration_delay.timeout_seconds', 300
> Target group helpers

- lib/convection/model/template.rb
Fixes the diff output for non-Resource parts of a CF template.
The Mapings section of CloudFormation templates is treated the same way
by the diff flattener as the Resources section.  Unfortunately, when
updating the diff to be smart enough to know about updates which require
replacement, the Resource Type was added to the flattened key
unconditionally.  Since Mappings (and other not-Resources) have no
"Type" key, this meant an empty hash was added where the Type belonged.
To fix this, we now just don't put the Type in the flattened hash key
if there isn't one.
> Fix diff for Mappings

- lib/convection/control/stack.rb
- lib/convection/model/template/resource/aws_iam_role.rb
The purpose of this is to enable creation of an IAM role with a
user-defined name.  Normally, when you tell CloudFormation to create a
role named "MyRole", it actually creates a role named
"mycloudname-MyRole-RANDOMCHARS".  This change allows a user to
explicitly create a role named "MyRole".
> Add RoleName property to iam_role

- spec/convection/control/stack/after_create_tasks_spec.rb
- spec/convection/control/stack/after_delete_tasks_spec.rb
- spec/convection/control/stack/after_update_tasks_spec.rb
- spec/convection/control/stack/before_create_tasks_spec.rb
- spec/convection/control/stack/before_delete_tasks_spec.rb
- spec/convection/control/stack/before_update_tasks_spec.rb
- spec/convection/control/stack_spec.rb
- spec/ec2_client_context.rb
This changes the `describe_availability_zones` double so that it returns
a list of availability_zones.
Fixes #229
> Fix #229 -- Return a list a availability zones

- bin/convection
See also #223 and #224.
#224 didn't work since this is where the undefined method error is actually raised. The PR attempted fixing it at the source of input not where the call was made.
> Fix #223 - Cast string error messages to runtime error

- bin/convection
- lib/convection/control/stack.rb
```$ bundle exec convection help describe-resources
Usage:
convection describe-resources --stack=STACK
Options:
[--cloudfile=CLOUDFILE]       
--stack=STACK                 # The stack to be described
[--type=TYPE]                 # An optional filter on the types of resources to be described
[--properties=one two three]  # A space-separated list of properties to include in the output
[--format=FORMAT]             
Describe resources for a stack
```
Example usage:
`bundle exec convection describe-resources --stack vpc --type 'AWS::EC2::Subnet' --properties AvailabilityZone CidrBlock`
> Introduce a describe-resources subcommand for stack interrogation

- lib/convection/model/cloudfile.rb
- spec/convection/control/stack_spec.rb
- spec/convection/model/cloudfile_spec.rb
This change will only pass the `exclude_availability_zones option` to the `Stack` controller if the option is set in the Cloudfile.
This address #234 which was introduced in #232.
@erran-r7 @rdickey-r7
> Only pass exclude_availability_zones option if set

- bin/convection
Commit a7c43b71c7f93c9250877155cae9840e52c3db4a broke error message printing by trying to print a variable that doesn't exist.  This fixes that glitch.
> Print out error message correctly when there is one

- lib/convection/model/template/resource/aws_logs_subscription_filter.rb
Define `logs_subscription_filter` DSL for `AWS::Logs::SubscriptionFilter` (see:  http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-subscriptionfilter.html )
> Add AWS::Logs::SubscriptionFilter resource for streaming AWS CloudWatch logs to Kinesis/Lambda

- lib/convection/control/cloud.rb
We use "deleted" past tense when we should be using just "delete" in the status.
```
deleted  Delete remote stack example-corp-0-dnsproxysecondary
```
```
delete  Delete remote stack example-corp-0-dnsproxysecondary
```
> Fix verb tense of pre-"delete" status

- lib/convection/model/event.rb
Changes info messages to be cyan, rather than green.
Before:
After:
When running a `diff --vv`, it's sometimes hard to see one change in a
sea of unchanged stack info messages.  This is because the `compare` and
`create` and `update` look very similar given the color.  With this new
change, `compare` and `unchanged` will be cyan, but `create` and
`update` will continue to show as green.
This has been tested on both a black and a white background, so should
have minimal annoyance factor across a range of color palates.
Just run a `convection diff --vv`
Dance
> Make info messages cyan instead of green

- lib/convection/model/template/resource_property/aws_cloudfront_viewercertificate.rb
This adds support for using ACM certificates in CloudFront distributions.
New SSL certificates, even imported 3rd party certificates, use the new ACM certificate functionality in AWS.  This replaces the old IAM certificates.  To use these in convection, the CloudFormation `AcmCertificateArn` property must be used.
```ruby
cloudfront_distribution 'FooCloudFront' do
config do
...
viewer_certificate do
acm_certificate_arn 'arn:aws:acm:us-east-1:XXXXXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
ssl_support_method 'sni-only'
end
end
end
```
Converged a stack using this branch.
> Add the AcmCertificateArn property to CloudFront

- bin/convection
- lib/convection/control/cloud.rb
Adds a new option `--exclude-stacks [STACK_NAME] <[STACK_NAME]> ...` to the `convection diff` and `convection converge` operations. Any stacks specified therein (as a space-separated list of stack names) are removed from the `diff` or `converge` operation. If one or more specified stacks does not exist, that's an error.
This new option cannot be used in conjunction with either of the existing options `--stack-group` or `--stacks`.
Increased flexibility while deploying changes to environments.
> Add '--exclude-stacks' option for 'diff' and 'converge'

- .rubocop_todo.yml
- bin/convection
This gives power users to ability to export configuration to terraform by defining `#terraform_import_commands` and `#to_hcl_json` on their resource or resource collections.
This ties into #268 which added the ability to mark all resources in a stack with the "Retain" deletion policy. Doing so then performing `convection terraform-export` should leave users in a place where they have a clear exit strategy from CloudFormation jail convection.
> Create a terraform-export subcommand

- bin/convection
* `--[no-]confirm-root` will supress the warning when generating resources under the root terraform module path.
* `--[no-]overwrite` will force overwriting any existing tf.json files to be generated.
* `--[no-]skip` will force skipping generating any existing tf.json files.
> Add a few new flags to convection terraform-export

- .rubocop.yml
- bin/convection
- lib/convection/dsl/helpers.rb
- lib/convection/dsl/intrinsic_functions.rb
- lib/convection/dsl/terraform_intrinsic_functions.rb
Currently intrinsic functions are only being overridden for `Resource`s  and `ResourceCollection`s.
Intrinsic functions called from anywhere should be overridden by terraform intrinsic functions.
> Overload all users of IntrinsicFunctions

- lib/convection/dsl/terraform_intrinsic_functions.rb
AWS resources have a modular style type causing conversion to underscores to include slashes in place of colon-colon.
> Swap slashes for underscores when converting modular type

- bin/convection
Add support for using `Resource#additional_hcl_files`/`ResourceCollection#additional_hcl_files` to generate additional HCL files.
Usage:
```ruby
def additional_hcl_files
{
'hello_world.tf.json': { aws_s3_bucket: { mybucketname: { ... } } },
}
end
```
> Support a hash of additional hcl files to generate

- bin/convection
Currently resource collections must define `terraform_import_commands` and save an instance variable to use the `--module-path` flag. This passes it directly into the `additional_hcl_files` function.
> Pass :module_path through to additional_hcl_files

- lib/convection/model/template/resource/aws_ec2_route.rb
- lib/convection/model/template/resource/aws_ec2_route_table.rb
This adds support for exporting `AWS::EC2::Route` and `AWS::EC2::RouteTable` resources to Terraform. Terraform doesn't support importing `AWS::EC2::Route` objects, so you'll want to import Route Table resources, add Route resources, and then run `terraform plan` to check that everything's okay.
> Feature: EC2 Route Terraform support

- lib/convection/model/template/resource/aws_ec2_security_group.rb
This adds support for exporting `AWS::EC2::SecurityGroup` resources into Terraform. Additionally, it implements the `terraform_import_commands` method to support generating import scripts.
> Export aws_security_group to Terraform.

- lib/convection/model/template/resource/aws_iam_user.rb
@mfreebairn-r7 pointed out that we never fixed support for managed policy attachments before merging #288.
> fix: Support importing managed policies for IAM user resources

- bin/convection
This fixes a null pointer in `terraform-compare-resources`.
> Ixfay ypotay inway erraformtay omparecay esourcesray ubcommandsay

- .gitignore
- lib/convection/model/template/resource/aws_rds_db_cluster.rb
- lib/convection/model/template/resource/aws_rds_db_instance.rb
- spec/convection/model/template/resource/aws_rds_db_cluster_spec.rb
Added support for creating AWS::RDS::DBCluster resource. 
Added an rspec test for the new resource. 
Tested by creating a database cluster in the dev account.
> Adds support for creating AWS::RDS::DBCluster resource 

- lib/convection/model/template/resource/aws_rds_db_clusterparametergroup.rb
- spec/convection/model/template/resource/aws_rds_db__clusterparametergroup_spec.rb
Added support for AWS::RDS::DBClusterParameterGroup resource.
Added a rspec test for the new resource. 
Tested by creating a DB Cluster Parameter group  in the dev account.
>  Added support for AWS::RDS::DBClusterParameterGroup resource

- lib/convection/model/template/resource/aws_rds_db_instance.rb
Added a property 'db_cluster_identifier' for DBClusterIdentifier in the rds database instance resource.
> Added property for DBClusterIdentifier in AWS::RDS::DBInstance resource.

- lib/convection/model/template/resource/aws_rds_db_cluster.rb
- spec/convection/model/template/resource/aws_rds_db_cluster_spec.rb
VpcSecurityGroupsIds property had been mistyped as VPCSecurityGroupsIds.
> Fixed typo in VpcSecurityGroupIds property

- lib/convection/model/template/resource/aws_rds_db_instance.rb
A duplicate of the 'storage_encrypted' property was removed.
> Removed a duplicated property in AWS::RDS::DBInstance resource. 

- lib/convection/model/template/resource/aws_lambda_function.rb
- lib/convection/model/template/resource_property/aws_lambda_dead_letter_config.rb
- lib/convection/model/template/resource_property/aws_lambda_environment.rb
- lib/convection/model/template/resource_property/aws_lambda_function_dead_letter_config.rb
Add KmsKeyArn for environment variable encryption.
Add DeadLetterConfig for failure DeadLetterQueue use. (#256)
Add Taggable mixin to allow tags on lambdas.
Add ReservedConcurrentExecutions to set max concurrent executions.
I want to use tags and decided to fill in the other missing bits as well.
This is an updated version of #263	
```ruby
lambda_function 'MyLambda' do
handler 'lambda.handler'
runtime 'python2.7'
timeout 30
memory_size 128
kms_key_arn get_att('MyKmsKey', 'Arn')
concurrency 100
dead_letter_config do
target_arn get_att('MyDeadLetterQueue', 'Arn')
end
tag 'my_first_tag_key', 'tag_value'
tag 'my_second_tag_key, 'other_tag_value'
end
```
Of course you can use raw strings as well:
```ruby
kms_key_arn 'arn:aws:kms:us-east-1:XXXXXXXXXXXX:key/my-alias-or-uuid'
dead_letter_config …
```
> Add more properties to Lambda and make it taggable

- lib/convection/model/template/resource/aws_lambda_function.rb
- spec/convection/model/template/resource/lambdas_spec.rb
Replace `env` with `dead_letter_cfg` in the DeadLetterConfig block.
I noticed after the fact that `env` being referenced still, so the new `dead_letter_cfg` never gets used. 😞
> Fix dead letter config for lambda function

- .rubocop.yml
- lib/convection/model/diff.rb
- lib/convection/model/template.rb
- spec/convection/model/template/template_spec.rb
This makes it clear when a DeletionPolicy is set to Retain, which resources will be kept.
We are starting to migrate the last of our convection work to terraform and want it to be clear when resources are kept.
> Adding retain highlight to output for deletionpolicy
