rapid7/convection

- lib/convection/model/template/resource.rb
- lib/convection/model/template/resource/aws_cloud_watch_alarm.rb
- lib/convection/model/template/resource/aws_sns_topic.rb
This commit adds both sns topic and cloud watch alarms
> Adds alarms

- README.md
- Rakefile
- convection.gemspec
- lib/convection/model/template.rb
- lib/convection/model/template/condition.rb
- test/convection/model/test_conditions.rb
- test/convection/model/test_template.rb
- test/test_helper.rb
This pull request adds native Convection support for CF Conditions.  
README.md updated accordingly.
Tests added:
1) condition blocks generate the correct JSON
2) test that resources can use conditions
3) test that resource properties can use conditions
> Support for CloudFormation Conditions in Convection

- lib/convection/model/template/resource/aws_ec2_instance.rb
- lib/convection/model/template/resource/aws_rds_db_instance.rb
- lib/convection/model/template/resource/aws_rds_db_security_group.rb
> Adds ec2 instance profile

- lib/convection/control/cloud.rb
- lib/convection/model/cloudfile.rb
This commit adds configurable splay time beteen each stack converge
To enable add the following to the Cloudfile:
```
splay 10
```
> Adds ability to configure the splay/sleep

- example/rds.rb
- example/trust_cloudtrail.rb
- lib/convection/model/diff.rb
- lib/convection/model/mixin/protocol.rb
- lib/convection/model/template.rb
- lib/convection/model/template/resource/aws_iam_role.rb
- test/convection/model/test_loggroups.rb
- test/convection/model/test_rds.rb
- test/convection/model/test_validation.rb
- test/test_helper.rb
This is in preperation in adding this repo to TravisCI.  I wanted to get all of the tests passing or as close as possible.
@aburke-r7 There are a few failures in [test_validation.rb](https://github.com/rapid7/convection/blob/master/test/convection/model/test_validation.rb).  Can you look at fixing these?
```
Offenses:
test/convection/model/test_validation.rb:7:3: C: Method has too many lines. [32/29]
def test_within_limits
^^^
test/convection/model/test_validation.rb:95:3: C: Method has too many lines. [41/29]
def test_mappings
^^^
test/convection/model/test_validation.rb:167:3: C: Method has too many lines. [35/29]
def test_parameters
^^^
```
> Fixes spacing to make rubocop happier

- lib/convection/model/template/resource/aws_ec2_security_group.rb
Adds a `destination` attribute for egress security groups.
> Add security group destination attribute

- convection.gemspec
- lib/convection/version.rb
Consuming the entire readme.md made a mess out of rubygems.org.
Trying to clean it up.
> issue-74 Redoing the description and summary.

- lib/convection/model/template/resource/aws_ec2_vpc_endpoint.rb
- test/convection/model/test_vpc_endpoint.rb
This is the proposed API:
```
ec2_vpc_endpoint 'TestVpcEndpoint' do
service 's3'
vpc 'vpc-foo'
route_tables %w(table1 table2)
allow do
s3_resource 'bucket-bar', '*'
action 's3:GetObject'
end
end
```
> Support VpcEndpoint

- lib/convection/model/template/resource/aws_lambda_permission.rb
- test/convection/model/test_permission.rb
> Create an AWS::Lambda::Permission resource

- .rubocop_todo.yml
- lib/convection/control/stack.rb
- lib/convection/model/cloudfile.rb
- test/convection/tasks/test_after_create_tasks.rb
- test/convection/tasks/test_after_delete_tasks.rb
- test/convection/tasks/test_before_create_tasks.rb
- test/convection/tasks/test_before_delete_tasks.rb
- test/convection/tasks/test_ec2_vpc.rb
- test/test_helper.rb
See also #114 (original issue) and #119 (accidentally merged/pushed a merge from an incorrect base branch).
> Support stack life cycle tasks (#114 and #119)

- lib/convection/model/template/resource/aws_iam_role.rb
> Fix #129 - Add an assume_role_policy DSL method to iam_role

- README.md
Thoughts @jmanero-r7 @athompson-r7 @bcall-r7?
> Add information around versioning/branching

- lib/convection.rb
```ruby
stack = Convection.stack('EC2 VPC Test Stack', template) do
fail ArgumentError, "I'm never even thrown!"
end
stack = Convection::Control::Stack.new('EC2 VPC Test Stack', template) do
after_create_task MyTask.new
end
```
```ruby
stack = Convection.stack('EC2 VPC Test Stack', template) do
after_create_task MyTask.new
end
```
> Update `Convection.stack` to accept a configuration block

- README.md
- lib/convection.rb
- lib/convection/control/cloud.rb
- lib/convection/control/stack.rb
- lib/convection/model/cloudfile.rb
> Start #116 - Update Ruby API documentation

- docs/relationship-to-cloudformation.md
- docs/template.html
> Add some basic CloudFormation relationship examples

- lib/convection/model/template/resource/aws_lambda_alias.rb
- lib/convection/model/template/resource/aws_lambda_function.rb
- lib/convection/model/template/resource/aws_lambda_version.rb
- lib/convection/model/template/resource_property/aws_lambda_function_code.rb
This PR just defines extra resources and properties to better support AWS Lambda
> Additional support for Lambda resources

- lib/convection/control/cloud.rb
- lib/convection/control/stack.rb
- lib/convection/model/cloudfile.rb
Rate limiting performance improvements
> Performance Improvements

- lib/convection/model/template/resource_property/aws_cloudfront_defaultcachebehavior.rb
Add new params
DefaultTTL and Compress
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-defaultcachebehavior.html
> Add DefaultTTL and Compress

- lib/convection/model/template/resource/aws_auto_scaling_auto_scaling_group.rb
Support the `TargetGroupARNs` resource property.
> Add target_group_arns to asg resource

- docs/getting-started.md
> Fix #243 - minor getting started guide update

- lib/convection/model/template/resource_property/aws_ec2_block_device_mapping.rb
Fix #236.
Credit here should go to @SuperGeno, since they even found the root cause here. 🎉
> Use ebs over non-existent config variable

- lib/convection/model/mixin/policy.rb
- spec/convection/model/template/resource/policy_document_spec.rb
Fix #237.
Add a failing spec to reproduce #237 then fix it!
cc @SuperGeno
> Support setting Id on policy documents

- lib/convection/model/template/resource_attribute/update_policy.rb
> Add ability to wait on resource signals in elb update

- lib/convection/model/template/resource/aws_auto_scaling_launch_configuration.rb
> Add block device mapping helper to asg launch_config

- lib/convection/dsl/intrinsic_functions.rb
- lib/convection/model/template/resource/aws_api_gateway_account.rb
- lib/convection/model/template/resource/aws_api_gateway_api_key.rb
- lib/convection/model/template/resource/aws_api_gateway_authorizer.rb
- lib/convection/model/template/resource/aws_api_gateway_base_path_mapping.rb
- lib/convection/model/template/resource/aws_api_gateway_client_certificate.rb
- lib/convection/model/template/resource/aws_api_gateway_deployment.rb
- lib/convection/model/template/resource/aws_api_gateway_method.rb
- lib/convection/model/template/resource/aws_api_gateway_model.rb
- lib/convection/model/template/resource/aws_api_gateway_resource.rb
- lib/convection/model/template/resource/aws_api_gateway_rest_api.rb
- lib/convection/model/template/resource/aws_api_gateway_stage.rb
- lib/convection/model/template/resource/aws_api_gateway_usage_plan.rb
- lib/convection/model/template/resource/aws_api_gateway_usage_plan_key.rb
- lib/convection/model/template/resource_property/aws_api_gateway_api_key_stage_key.rb
- lib/convection/model/template/resource_property/aws_api_gateway_deployment_stage_description.rb
- lib/convection/model/template/resource_property/aws_api_gateway_deployment_stage_description_method_setting.rb
- lib/convection/model/template/resource_property/aws_api_gateway_deployment_stage_method_setting.rb
- lib/convection/model/template/resource_property/aws_api_gateway_method_integration.rb
- lib/convection/model/template/resource_property/aws_api_gateway_method_integration_integration_response.rb
- lib/convection/model/template/resource_property/aws_api_gateway_method_method_response.rb
- lib/convection/model/template/resource_property/aws_api_gateway_rest_api_s3_location.rb
- lib/convection/model/template/resource_property/aws_api_gateway_usage_plan_api_stage.rb
- lib/convection/model/template/resource_property/aws_api_gateway_usage_plan_quota_settings.rb
- lib/convection/model/template/resource_property/aws_api_gateway_usage_plan_throttle_settings.rb
There are a lot here and I haven't tested all of them but the ones I
have seemed to work.  Also added the Fn::Sub intrinsic function because
it's used by amazon in one of the examples for how api gateway can be
implemented, and I tested that the non-hash version works.
> Implement API Gateway resources and properties

- lib/convection/model/template/resource/aws_auto_scaling_scheduled_action.rb
Add a resource for http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-as-scheduledaction.html
I want to use an ASG with scheduled scale up and down.
Daily schedule at midnight EDT
```ruby
scheduled_action 'MyScheduledActionScaleUp' do
auto_scaling_group_name 'MyAutoScalingGroup'
desired_capacity 5
max_size 5
min_size 1
recurrence '0 10 * * *' # cron syntax: daily at 10:00 UTC
end
```
Scale down after a few hours:
```ruby
scheduled_action 'MyScheduledActionScaleDown' do
auto_scaling_group_name 'MyAutoScalingGroup'
desired_capacity 1
max_size 1
min_size 1
recurrence '0 13 * * *' # cron syntax: daily at 13:00 UTC
end
```
> Add resource for AWS::AutoScaling::ScheduledAction

- lib/convection/model/template/resource/aws_ecr_repository.rb
> Add ecr repo

- bin/convection
- convection.gemspec
- lib/convection/dsl/terraform_intrinsic_functions.rb
Dynamically these methods into all Template, Resource, and ResourceCollection instances we operate on when writing HCL for terraform usage.
>  Add intrinsic function overrides to use with terraform export

- bin/convection
- lib/convection/terraform/ext/stack.rb
Override `Stack#cloud` and `Stack#region` under the `terraform-export` command to us terraform interpolation.
> 🐒 Monkey patch #region/#cloud in terraform export

- bin/convection
```sh
bundle exec convection terraform-compare-resources \
--stack-name acmecorp-staging-web-app \
--stack-region ap-northeast-1 \
--state-region us-east-1 \
--state s3://my-state-bucket/ap-northeast-1/staging.tfstate
bundle exec convection terraform-compare-resources \
--stack-name acmecorp-prod-web-app \
--stack-region us-east-1 \
--state ~/terraform-my-project/us-east-1/production.tfstate
```
> Check for presence of stack resources within terraform state

- bin/convection
> Save terraform import commands to script

- bin/convection
- lib/convection/model/template/resource/aws_route53_recordset.rb
> Create terraform import command/hcl for basic route53 records

- bin/convection
Support importing lambda permissions with non-standard permission names.
> Permission resource name

- bin/convection
Add support for omitting proposed diffs from compare output when terraform state has parent resource.
> Prompt user for associated resource for policy resources

- lib/convection/model/template.rb
- lib/convection/model/template/resource/aws_iam_user.rb
This includes managed policy ARN and inline policy support.
> Add terraform export support for aws_iam_user

- lib/convection/model/template/resource/aws_s3_bucket.rb
- lib/convection/model/template/resource/aws_s3_bucket_policy.rb
> Support aws_s3_bucket terraform export

- lib/convection/model/template/resource/aws_cloud_watch_alarm.rb
> added to_hcl support for aws_cloud_watch_alarm

- lib/convection/model/template/resource_property/aws_cloudfront_forwardedvalues.rb
- lib/convection/model/template/resource_property/aws_cloudfront_forwardedvalues_cookies.rb
> Add CloudFront ForwardedValues Cookies resource attribute

- bin/convection
> Fix lookup of resource in TF state where fuzzy matching used

- lib/convection/model/template/resource/aws_dynamodb_table.rb
- spec/convection/model/template/resource/aws_dynamodb_table_spec.rb
Adding a resource for AWS:DynamoDB:Table. 
Also adding an rspec test for it.
> PD-17885: Adding dynamodb table resource and rspec or it.
